// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbdjsderwohkhymwgjsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZGpzZGVyd29oa2h5bXdnanNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzQ0MzUsImV4cCI6MjA2MTgxMDQzNX0.x3m8F6L6tf3z2lmcimNXqIPS9eBUPm8--Q_ACHCvtRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);